---

# create virtualenv
- name: create virtualenv
  shell:
    chdir: /home/{{ user_name }}/dataperu-etl
    cmd: virtualenv -p python3.7 venv

# install python dependencies for etl process
- name: install python dependencies for etl process
  pip:
    requirements: /home/{{ user_name }}/dataperu-etl/requirements.txt
    virtualenv: /home/{{user_name}}/dataperu-etl/venv

# execute pipelines
- name: execute pipelines
  async: 21600
  poll: 1800
  shell:
    chdir: /home/{{ user_name }}/dataperu-etl
    cmd: . /home/{{ user_name }}/dataperu-etl/venv/bin/activate && python -m etl.__init__ ../datasets
  environment:
    CLICKHOUSE_URL: "{{ lookup('env', 'CLICKHOUSE_URL') }}"
    CLICKHOUSE_USERNAME: "{{ lookup('env', 'CLICKHOUSE_USERNAME') }}"
    CLICKHOUSE_DATABASE: "{{ lookup('env', 'CLICKHOUSE_DATABASE') }}"
    CLICKHOUSE_PASSWORD: "{{ lookup('env', 'CLICKHOUSE_PASSWORD') }}"

