---

# clone tesseract repo
- name: clone dataperu-tesseract repo
  ansible.builtin.git:
    repo: git@github.com:dataperu/dataperu-tesseract.git
    version: "{{git_branch}}"
    dest: /home/{{user_name}}/dataperu-tesseract
    accept_hostkey: yes
    key_file: /home/{{user_name}}/.ssh/id_dataperu_tesseract

# clone etl repo
- name: clone dataperu-etl repo
  ansible.builtin.git:
    repo: git@github.com-etl:dataperu/dataperu-etl.git
    version: "{{git_branch}}"
    dest: /home/{{user_name}}/dataperu-etl
    accept_hostkey: yes
    key_file: /home/{{user_name}}/.ssh/id_dataperu_etl