---
# update dependencies on linux
- name: update dependencies of linux packages
  apt:
    update_cache: yes

# add python3 repository
- name: add python3 repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

# install common packages
- name: install common packages
  apt:
    pkg:
    - acl
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - dirmngr
    - fonts-liberation
    - git
    - libappindicator3-1
    - libasound2
    - libatk-bridge2.0-0
    - libcups2
    - libgbm1
    - libgcc1
    - libnss3
    - libx11-xcb1
    - libxss1
    - python3.7-dev
    - python3-pip
    - python3.7-venv
    - python3-wheel
    - unzip
    - virtualenv
    - wget
    - xdg-utils

# install common python packages
- name: install common python packages
  pip:
    name:
      - psycopg2-binary
    executable: pip3
